######################################################################
##
## Filename: tb_system.udo
## Created on: Wed Feb 22 08:27:23 Romance Standard Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
